### ISSUE TITLE
支持 vue 2？

### ISSUE THREAD

**Issue by ModyQyW** [satrong/uni-ui-components-types#2]
能否支持 vue 2 呢？

**Comment by satrong** [comment]
这个只是将 vetur 的代码提示文件转成 ts 的声明文件，与 vue 的版本没有直接的关系

**Comment by ModyQyW** [comment]
我提出这个 issue 的本意和 https://github.com/satrong/uni-base-components-types/issues/2 一样。我觉得可以在那边统一讨论。
